/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacepokedex;

/**
 * autores:
 * João Pedro Banhato Pereira (202165506B)
 * Lucas de Oliveira Varino (202165090A)
 */
public class InterfaceRegistraPokemon extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceInicial
     */
    public InterfaceRegistraPokemon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criaPokemon = new javax.swing.JButton();
        registrarPokemon = new javax.swing.JLabel();
        nomePokemon = new javax.swing.JLabel();
        inputNomePokemon = new javax.swing.JTextField();
        altura = new javax.swing.JLabel();
        inputAlturaPokemon = new javax.swing.JTextField();
        pesoPokemon = new javax.swing.JLabel();
        inputPesoPokemon = new javax.swing.JTextField();
        pokedex = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        criaPokemon.setBackground(new java.awt.Color(102, 204, 255));
        criaPokemon.setText("Registrar");
        criaPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criaPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(criaPokemon);
        criaPokemon.setBounds(200, 360, 90, 24);

        registrarPokemon.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        registrarPokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarPokemon.setText("REGISTRAR POKEMON");
        getContentPane().add(registrarPokemon);
        registrarPokemon.setBounds(170, 230, 160, 23);

        nomePokemon.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        nomePokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomePokemon.setText("Nome:");
        getContentPane().add(nomePokemon);
        nomePokemon.setBounds(140, 260, 60, 23);

        inputNomePokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomePokemonActionPerformed(evt);
            }
        });
        getContentPane().add(inputNomePokemon);
        inputNomePokemon.setBounds(210, 260, 110, 24);

        altura.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        altura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        altura.setText("Altura:");
        getContentPane().add(altura);
        altura.setBounds(140, 290, 60, 23);

        inputAlturaPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlturaPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(inputAlturaPokemon);
        inputAlturaPokemon.setBounds(210, 290, 60, 24);

        pesoPokemon.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        pesoPokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoPokemon.setText("Peso:");
        getContentPane().add(pesoPokemon);
        pesoPokemon.setBounds(150, 320, 50, 23);

        inputPesoPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPesoPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(inputPesoPokemon);
        inputPesoPokemon.setBounds(210, 320, 60, 24);

        pokedex.setIcon(new javax.swing.ImageIcon("C:\\Users\\jpbba\\Documents\\Coding\\Ufjf\\OO\\trabalho-oo\\Trabalho-OOP\\PokedexOO\\img\\pokedex-png-transparent-png.png")); // NOI18N
        getContentPane().add(pokedex);
        pokedex.setBounds(20, 15, 840, 639);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criaPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criaPokemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criaPokemonActionPerformed

    private void inputNomePokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomePokemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomePokemonActionPerformed

    private void inputAlturaPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlturaPokemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAlturaPokemonActionPerformed

    private void inputPesoPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPesoPokemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPesoPokemonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceRegistraPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceRegistraPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceRegistraPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceRegistraPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceRegistraPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altura;
    private javax.swing.JButton criaPokemon;
    private javax.swing.JTextField inputAlturaPokemon;
    private javax.swing.JTextField inputNomePokemon;
    private javax.swing.JTextField inputPesoPokemon;
    private javax.swing.JLabel nomePokemon;
    private javax.swing.JLabel pesoPokemon;
    private javax.swing.JLabel pokedex;
    private javax.swing.JLabel registrarPokemon;
    // End of variables declaration//GEN-END:variables

    
    
}
