/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacepokedex.admin;

import com.mycompany.interfacepokedex.InterfaceInicial;
import com.mycompany.pokedexoo.users.Jogador;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * autores:
 * João Pedro Banhato Pereira (202165506B)
 * Lucas de Oliveira Varino (202165090A)
 */
public class InterfaceAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceInicial
     */
    public InterfaceAdmin() throws FileNotFoundException {
        initComponents();
        this.setSize(1000, 800);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws FileNotFoundException {

        listaJogadores = new javax.swing.JComboBox<>();
        selecionaJogador = new javax.swing.JButton();
        admin = new javax.swing.JLabel();
        jogador = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        pokedex = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        listaJogadores.setModel(new javax.swing.DefaultComboBoxModel<>(Jogador.getAllNomes()));
        listaJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaJogadoresActionPerformed(evt);
            }
        });
        getContentPane().add(listaJogadores);
        listaJogadores.setBounds(240, 290, 120, 26);

        selecionaJogador.setBackground(new java.awt.Color(51, 255, 51));
        selecionaJogador.setText("Confirmar");
        selecionaJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaJogadorActionPerformed(evt);
            }
        });
        getContentPane().add(selecionaJogador);
        selecionaJogador.setBounds(140, 360, 110, 24);

        admin.setBackground(new java.awt.Color(0, 153, 51));
        admin.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        admin.setForeground(new java.awt.Color(0, 204, 51));
        admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin.setText("ADMIN 1");
        getContentPane().add(admin);
        admin.setBounds(200, 230, 90, 23);

        jogador.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jogador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jogador.setText("Jogadores:");
        getContentPane().add(jogador);
        jogador.setBounds(130, 290, 110, 23);

        sair.setBackground(new java.awt.Color(255, 0, 0));
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(260, 360, 100, 24);

        pokedex.setIcon(new javax.swing.ImageIcon("img/pokedex.png")); // NOI18N
        getContentPane().add(pokedex);
        pokedex.setBounds(20, 15, 840, 639);

        pack();
    }// </editor-fold>//

    private void listaJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaJogadoresActionPerformed
        // combo-box com os jogadores para o admin selecionar
    }//GEN-LAST:event_listaJogadoresActionPerformed

    private void selecionaJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaJogadorActionPerformed
        try {
            // seleciona um jogador
            String jogadorSelecionado = listaJogadores.getSelectedItem().toString();
            Jogador.setNomeAtual(jogadorSelecionado);
            Jogador.setJogadorAtualByName(jogadorSelecionado);
            // e vai para sua tela de edicao, primeiro aos treinadores
            this.dispose();
            InterfaceAdminTreinador interfaceAdminTreinador = new InterfaceAdminTreinador();
            interfaceAdminTreinador.setVisible(true);
        } catch (FileNotFoundException ex) {
            System.out.println("Nao foi possivel encontrar o arquivo.");
        }
    }//GEN-LAST:event_selecionaJogadorActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        try {
            // volta para a InterfaceInicial
            this.dispose();
            InterfaceInicial interfaceInicial = new InterfaceInicial();
            interfaceInicial.setVisible(true);
        } catch (FileNotFoundException ex) {
            System.out.println("Nao foi possivel encontrar o arquivo.");
        }
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfaceAdmin().setVisible(true);
                } catch (FileNotFoundException ex) {
                    System.out.println("Nao foi possivel encontrar o arquivo.");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JLabel jogador;
    private javax.swing.JComboBox<String> listaJogadores;
    private javax.swing.JLabel pokedex;
    private javax.swing.JButton sair;
    private javax.swing.JButton selecionaJogador;
    // End of variables declaration//GEN-END:variables

    
    
}
